---
output:
  officedown::rdocx_document:
    keep_md: no
    reference_docx: ../www/Epidemiology_and_Psychiatric_Sciences.docx
    tables:
      caption:
        pre: 'Table '
        sep: '. '
csl:          ../www/who-europe-harvard.csl
bibliography: ../www/Subestudio_confinamiento.bib
editor_options: 
  chunk_output_type: console
params:
  extra: no
---

```{r setup, include=FALSE}
library(pacman)
p_load(knitr)


# File system constants:

ROOT_DIR <- ".."
OUT_DIR  <- "output"
SRC_DIR  <- "src"
SRC_FILE <- file.path(SRC_DIR, "Lockdown_analysis.R")


# opts_knit$set(root.dir = ROOT_DIR)

# Knitr output configuration:

opts_chunk$set(
  echo       = FALSE,
  results    = 'asis',
  warning    = FALSE,
  message    = FALSE,
  cache      = TRUE,
  fig.width  = 16.59/2.54,
  fig.height = 4.5
)

options(digits = 3)
```


```{r read-chunks, cache=FALSE}
read_chunk(SRC_FILE)
```


```{r script-configuration, cache=FALSE}
```


```{r includes, cache=FALSE}
```


```{r constants}
```


```{r load-data}
```


```{r compute-interview-dates}
```


```{r subset-cases}
```


```{r compare-excluded-cases}
```


```{r preprocess-data}
```


```{r create-var-labels}
```


```{r set-flextable-wd, cache=FALSE}
# This is necessary for flextable to work:
opts_knit$set(root.dir = file.path(getwd(), OUT_DIR))
```


```{r missing-responses}
```


```{r time-varying-predictors}
```


```{r standardize-predictors}
```


```{r subset-predictors}
```


```{r var-descriptives}
```


```{r depression-dataset}
```


```{r depression-prevalence-estimates}
```


```{r depression-association-population}
```


```{r suicidal-dataset}
```


```{r suicidal-prevalence-estimates}
```


```{r suicidal-association-population}
```


```{r prevalence-estimates-collapsed}
```


```{r prevalence-values}
```


```{r depression-selection-no-pre}
```


```{r depression-no-pre-contingency}
```


```{r univariate-tests-depression}
```


```{r predictor-selection-depression}
```


```{r ordinal-linearity-tests-depression}
```


```{r stepwise-glm-depression, results='hide'}
```


```{r conclusions-pre-computations-depression}
```


```{r depression-coefficients}
```


```{r suicidal-selection-no-pre}
```


```{r suicidal-no-pre-contingency}
```


```{r univariate-tests-suicidal}
```


```{r predictor-selection-suicidal}
```


```{r drop-complete-separation-terms-suicidal}
```


```{r ordinal-linearity-tests-suicidal}
```


```{r stepwise-glm-suicidal, results='hide'}
```


```{r conclusions-pre-computations-suicidal}
```


```{r suicidal-coefficients}
```


```{r descriptive-stats-table, tab.id="descriptive-stats-table", tab.cap=CAPTION_DESC_VARIABLES, cache=FALSE}
total_descriptives_out
```


```{r prevalence-table, tab.id="prevalence-table", tab.cap=CAPTION_PREVALENCES, cache=FALSE}
prevalence_table_output
```

\newpage


```{r depression-coefficients-table, tab.id="depression-coefficients-table", tab.cap=CAPTION_DEPRESSION_FIT_NEW_TERMS, cache=FALSE}
depression_coefficients_table
```

\newpage


```{r suicidal-coefficients-table, tab.id="suicidal-coefficients-table", tab.cap=CAPTION_SUICIDAL_FIT_NEW_TERMS, cache=FALSE}
suicidal_coefficients_table
```


```{r session-info, results='hide'}
```
