---
title: "Distribución de edades"
output:
  html_notebook:
    df_print: paged
    toc: yes
    toc_float: yes
    code_folding: hide
csl:          ../www/who-europe-harvard.csl
bibliography: ../www/Subestudio_confinamiento.bib
params:
  extra: no
editor_options: 
  chunk_output_type: inline
---

```{r setup}
library(pacman)
p_load(knitr)


# File system constants:

ROOT_DIR <- ".."
OUT_DIR  <- "output"
SRC_DIR  <- "src"
SRC_FILE <- file.path(SRC_DIR, "Lockdown_analysis.R")


# opts_knit$set(root.dir = ROOT_DIR)

# Knitr output configuration:

opts_chunk$set(
  echo       = TRUE,
  results    = 'asis',
  warning    = FALSE,
  message    = FALSE,
  cache      = TRUE,
  fig.width  = 16.59/2.54,
  fig.height = 4.5
)

options(digits = 3)
```


```{r read-chunks, cache=FALSE}
read_chunk(SRC_FILE)
```


```{r script-configuration, cache=FALSE}
```


```{r includes, cache=FALSE}
```


```{r constants}
```


```{r load-data}
```


```{r compute-interview-dates}
```


```{r subset-cases}
```


```{r compare-excluded-cases}
```


```{r preprocess-data}
```


```{r create-var-labels}
```


```{r}
limits <- dataset_outcomes %>% summarize(range(age_pre)) %>% pull()
min    <- limits[1] %>% floor()
max    <- limits[2] %>% ceiling()


base_hist <- dataset_outcomes %>% ggplot(aes(x = age_pre))

annotation <- geom_vline(
    xintercept = 50,
    color = "black"
  )
```


# Histograma en intervalos de un año de edad

```{r}
base_hist + geom_histogram(binwidth = 1) + annotation
```


# Histograma en intervalos de diez años de edad

```{r}
base_hist + geom_histogram(binwidth = 10) + annotation
```


# Recuento de casos por décadas

```{r, results='markup'}
cut_points <- floor(min / 10):ceiling(max / 10) * 10

dataset_outcomes %>%
  transmute(age_group = age_pre %>% cut(cut_points)) %>%
  count(age_group)
```


# Divisones propuestas

* En 18-29, 30-49, 50+:

```{r}
cut_points <- c(18,  30, 50, 90)

dataset_outcomes %>%
  transmute(age_group = age_pre %>% cut(cut_points, right = FALSE)) %>%
  count(age_group)
```


* En 18-24, 35-49, 50+:

```{r}
cut_points <- c(18,  35, 50, 90)

dataset_outcomes %>%
  transmute(age_group = age_pre %>% cut(cut_points, right = FALSE)) %>%
  count(age_group)
```
